/**
 * Code generation using Google Gemini API (free tier).
 */

import { GoogleGenerativeAI } from '@google/generative-ai';
import { TechnicalSpec, PaperMetadata, DifficultyScore, GeneratedCode } from '@/types';

function getClient() {
  const apiKey = process.env.GEMINI_API_KEY || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('No LLM API key configured');
  return new GoogleGenerativeAI(apiKey);
}

function buildPrompt(metadata: PaperMetadata, spec: TechnicalSpec, score: DifficultyScore): string {
  const ambiguityNotes = score.ambiguousFields
    .map(f => `- ${f.fieldName}: ${f.issue}`)
    .join('\n');

  return `You are generating a research paper reproduction starter repository.

Paper: "${metadata.title}"
Authors: ${metadata.authors.join(', ')}

Technical Spec:
${JSON.stringify(spec, null, 2)}

Ambiguous fields requiring verification:
${ambiguityNotes || 'None - high confidence on most fields.'}

Replication Difficulty Score: ${score.score}/10

Generate a Python starter repository with EXACTLY these 5 files.
For each file use this format:
===FILE: filename===
<contents>
===END===

Files: model.py, train.py, data_loader.py, requirements.txt, NOTES.md

CRITICAL RULES:
- Add # NOTE comments wherever an ambiguous or inferred value is used
- Example: # NOTE: learning rate not explicitly stated - using 1e-4 as default, verify against paper
- If a value is unknown, use a sensible placeholder with a # TODO comment
- Use standard PyTorch conventions
- Keep code clean, readable, well-commented
- The code must be genuinely runnable as a starting point`;
}

export async function generateRepoCode(
  metadata: PaperMetadata,
  spec: TechnicalSpec,
  score: DifficultyScore
): Promise<GeneratedCode> {
  const client = getClient();
  const model = client.getGenerativeModel({ model: 'gemini-2.0-flash' });

  const result = await model.generateContent({
    contents: [{ role: 'user', parts: [{ text: buildPrompt(metadata, spec, score) }] }],
    generationConfig: {
      temperature: 0.2,
      maxOutputTokens: 8192,
    },
  });

  const text = result.response.text();
  const files = parseFiles(text);

  // Add README
  files.push({
    path: 'README.md',
    content: generateReadme(metadata, spec, score),
    language: 'markdown',
  });

  return { files };
}

function parseFiles(raw: string): { path: string; content: string; language: string }[] {
  const files: { path: string; content: string; language: string }[] = [];
  const regex = /===FILE: ([^\n]+)===\n([\s\S]*?)===END===/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(raw)) !== null) {
    const [, filename, content] = match;
    files.push({
      path: filename.trim(),
      content: content.trim(),
      language: filename.endsWith('.py') ? 'python' : filename.endsWith('.md') ? 'markdown' : 'text',
    });
  }

  if (files.length === 0) {
    files.push({ path: 'generated_code.py', content: raw, language: 'python' });
  }

  return files;
}

function generateReadme(metadata: PaperMetadata, spec: TechnicalSpec, score: DifficultyScore): string {
  const ambiguityList = score.ambiguousFields
    .map(f => `- **${f.fieldName}** (${f.confidence}): ${f.issue}\n  - ${f.recommendation}`)
    .join('\n');

  return `# ${metadata.title}

> Generated by PaperForge - an honest research-paper-to-code scaffold.
> This is a starting scaffold, not a verified reproduction. Review all flagged ambiguities.

## Authors
${metadata.authors.join(', ')}

## Abstract
${metadata.abstract}

---

## Replication Difficulty Score: ${score.score}/10

${score.overallAssessment}

| Category | Clarity |
|---|---|
| Model Architecture | ${Math.round(score.breakdown.modelClarityScore * 100)}% |
| Dataset | ${Math.round(score.breakdown.dataClarityScore * 100)}% |
| Training Recipe | ${Math.round(score.breakdown.trainingClarityScore * 100)}% |
| Evaluation | ${Math.round(score.breakdown.evaluationClarityScore * 100)}% |

---

## Ambiguous Fields - Verify Before Relying on This Code

${ambiguityList || 'No significant ambiguities detected.'}

---

## Setup

\`\`\`bash
pip install -r requirements.txt
python train.py
\`\`\`

*Generated with PaperForge. Always verify flagged ambiguities against the original paper.*
`;
}
